#!/bin/sh 

DATABASE_FILE=.database
 
function db_clear() {
  rm -f "$DATABASE_FILE"
}
 
function db_set() {
  echo "$1,$2" >> "$DATABASE_FILE"
}
 
function db_get() {
  grep "^$1," "$DATABASE_FILE" | sed -e "s/^$1,//" | tail -n 1
}
 
function db_remove() {
  db_set $1 ""
}

db_clear
db_set p:14:name "And Agency"
db_set p:15:name "Wiretool app"
db_set p:16:name "Houdmoed"

db_get p:15:name