#!/bin/sh
source $DOTFILES/secrets.zsh
SLACK_API="https://slack.com/api"
HEADER_CONTENT_TYPE="Content-Type: application/json; charset=utf-8"
HEADER_AUTHORIZATION="Authorization: Bearer $SLACK_TOKEN"

if [[ $1 ]]; then
    if [ "$1" = "auto" ] || [ "$1" = "away" ]; then
      _setPresence $1       
    elif [ "$1" = "break" ]; then
        _setStatus "404 $1" ":coffee:"
        _setPresence "away"
    elif [ "$1" = "gone" ]; then
        _setStatus "410 $1" ":black_circle:"
        _setPresence "away"
    elif [ "$1" = "meeting" ]; then
         _setStatus "404 $1" ":spiral_calendar_pad:"
         _setPresence "auto"
    elif [ "$1" = "work" ]; then
         _setStatus "200 $1" ":face_with_cowboy_hat:"
         _setPresence "auto"
    else
        echo "Unknown argument supplied"
        _help
    fi
else
    echo "No argument supplied"
    _help
fi

_setStatus() {
   curl "$SLACK_API/users.profile.set" \
      --header "$HEADER_AUTHORIZATION" \
      --header "$HEADER_CONTENT_TYPE" \
      --data-raw "{
      \"profile\": {
         \"status_text\": \"$1\",
         \"status_emoji\": \"$2\",
         \"status_expiration\": 0
      }
   }"
}

_setPresence() {
   curl "$SLACK_API/users.setPresence" \
      --header "$HEADER_AUTHORIZATION" \
      --header "$HEADER_CONTENT_TYPE" \
      --data-raw "{
      \"presence\": \"$1\"
   }"
}

_help() {
   echo "[usage]: status <argument> <param>"
   echo "[info]: set your slack status and/or presence"
   echo "[arguments]:"
   echo "Set presence auto"
   echo "- status auto" 
   echo "Set presence away"
   echo "- status away" 
   echo "Set status break"
   echo "- status break" 
   echo "Set status gone"
   echo "- status gone" 
   echo "Set status meeting"
   echo "- status meeting" 
   echo "Set status work"
   echo "- status work" 
}