#!/bin/sh
source $DOTFILES/secrets.zsh
SLACK_API="https://slack.com/api"
HEADER_CONTENT_TYPE="Content-Type: application/json; charset=utf-8"
HEADER_AUTHORIZATION="Authorization: Bearer $SLACK_TOKEN"

_helpTable() {
echo "[info]: set your slack status and/or presence"
echo "---------------------------------------------"
column -t -t -s ':' << EOM
   info:usage:argument
   -----:-----:-----
   Set presence auto:status:auto
   Set presence away:status:away
   Set status break:status:break
   Set status gone:status:gone
   Set status meeting:status:meeting
   Set status work:status:work
EOM
}

_setStatus() {
   curl "$SLACK_API/users.profile.set" \
      --header "$HEADER_AUTHORIZATION" \
      --header "$HEADER_CONTENT_TYPE" \
      --data-raw "{
      \"profile\": {
         \"status_text\": \"$1\",
         \"status_emoji\": \"$2\",
         \"status_expiration\": 0
      }
   }"
}

_setPresence() {
   curl "$SLACK_API/users.setPresence" \
      --header "$HEADER_AUTHORIZATION" \
      --header "$HEADER_CONTENT_TYPE" \
      --data-raw "{
      \"presence\": \"$1\"
   }"
}

if [[ $1 ]]; then
    
    if [ "$1" = "auto" ] || [ "$1" = "away" ]; then
      _setPresence $1       
    elif [ "$1" = "break" ]; then
        _setStatus "404 $1" ":coffee:"
        _setPresence "away"
    elif [ "$1" = "gone" ]; then
        _setStatus "410 $1" ":black_circle:"
        _setPresence "away"
    elif [ "$1" = "meeting" ]; then
         _setStatus "404 $1" ":spiral_calendar_pad:"
         _setPresence "auto"
    elif [ "$1" = "work" ]; then
         _setStatus "200 $1" ":face_with_cowboy_hat:"
         _setPresence "auto"
    else
        echo "Unknown argument supplied"
        _helpTable
    fi

else
    echo "No argument supplied"
   _helpTable
fi
