#!/bin/sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  

nodefile=$PWD/package.json
composerfile=$PWD/composer.json

if [ -f "$nodefile" ]; then 
    echo "---- info nodejs"
    nodeversion=$($DOTTOOLS/version_package_node)
    echo "Detected node version $nodeversion"
    echo "You are using NODE $(node -v)"
    echo "---- switching node version"
    nvm use --lts
else 
    echo "no package.json found"
fi

if [ -f "$composerfile" ]; then 
    echo "---- info php"
    phpversion=$($DOTTOOLS/version_composer_php)
    currentphpversion=$(php -v | egrep -o '(PHP [0-9].[0-9].[0-9])')
    echo "Detected php version $phpversion"
    echo "You are using $currentphpversion"
    echo "---- please check if php needs changing"
else 
    echo "no composer.json found"
fi