#!/bin/sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  

if [[ $1 ]]; then
    
    if [ "$1" = "use" ]; then
        
        if [[ $2 ]]; then
            nvm use $2
        else
            nvm use --lts        
        fi

    elif [ "$1" = "version" ]; then
        echo $(nvm -v)
    else
        echo "Unknown argument supplied"
        _help
    fi
else
    echo "No argument supplied"
    _help
fi

_help() {
    echo "[usage]: nvm <argument> <param>"
	echo "[info]: several helpers for nvm"
    echo "[arguments]:"
    echo "Show current installed nvm version"
    echo "- nvm version" 
    echo "Switch to and use a specific nodejs version"
    echo "- nvm use <version | optional | default: --lts>" 
}