#!/bin/sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  

if [[ $1 ]]; then
    if [ "$1" = "use" ]; then
        
        if [[ $2 ]]; then
            nvm use $2
        else
            nvm use --lts        
        fi

    else
        
    fi
    elif [ "$1" = "version" ]; then
        echo $(nvm -v)
    fi
else
    echo "Action: nvm <argument> <param>"
    echo "available arguments:"
    echo "- version" 
    echo "- use <database>" 
    echo "- create <database>" 
    echo "- drop <database>"
fi


else
    echo "Action: nvm <argument> <param>"
    echo "available arguments:"
    echo "- version" 
    echo "- use <database>" 
    echo "- create <database>" 
    echo "- drop <database>"
fi

if [ "$1" = "use" ]; then
    if [ $2 == "lts" ]; then
        nvm use --lts
    else
        nvm use $1
    fi
elif [ "$1" = "version" ]; then
    echo $(nvm -v)
else
    echo "Action: nvm <argument> <param>"
    echo "available arguments:"
    echo "- version" 
    echo "- use <database>" 
    echo "- create <database>" 
    echo "- drop <database>"
fi


